INSERT INTO `books` (`key_slug`, `title`, `author`, `description`, `category`, `image`, `created_at`) VALUES
('the-name-of-the-wind', 'The Name of the Wind', 'Patrick Rothfuss', 'A fantasy novel following the life of Kvothe, a gifted young man who grows into a legendary figure.', 'Fantasy', 'name-of-the-wind.jpg', NOW()),
('the-way-of-kings', 'The Way of Kings', 'Brandon Sanderson', 'The first book in The Stormlight Archive, a high-fantasy series filled with intricate world-building and powerful characters.', 'Fantasy', 'way-of-kings.jpg', NOW()),
('the-eye-of-the-world', 'The Eye of the World', 'Robert Jordan', 'The first book in The Wheel of Time series, an epic tale of magic, prophecy, and the battle between good and evil.', 'Fantasy', 'eye-of-the-world.jpg', NOW()),
('mistborn', 'Mistborn', 'Brandon Sanderson', 'A gripping fantasy novel about a revolution in a world ruled by a seemingly immortal tyrant.', 'Fantasy', 'mistborn.jpg', NOW()),
('wizards-first-rule', 'Wizard\'s First Rule', 'Terry Goodkind', 'The first book in The Sword of Truth series, following the journey of Richard Cypher as he discovers his destiny.', 'Fantasy', 'wizards-first-rule.jpg', NOW()),

('red-white-royal-blue', 'Red, White & Royal Blue', 'Casey McQuiston', 'A romantic comedy about the First Son of the United States and a British prince who go from rivals to lovers.', 'Romance', 'red-white-royal-blue.jpg', NOW()),
('book-lovers', 'Book Lovers', 'Emily Henry', 'A witty, heartwarming romance following a literary agent and a brooding editor who keep running into each other.', 'Romance', 'book-lovers.jpg', NOW()),
('the-hating-game', 'The Hating Game', 'Sally Thorne', 'A charming enemies-to-lovers workplace romance between two competitive co-workers.', 'Romance', 'the-hating-game.jpg', NOW()),
('happy-place', 'Happy Place', 'Emily Henry', 'A second-chance romance about a once-perfect couple pretending to still be together during a vacation with friends.', 'Romance', 'happy-place.jpg', NOW()),
('funny-story', 'Funny Story', 'Emily Henry', 'A delightful and emotional romance about unexpected love and finding humor in heartbreak.', 'Romance', 'funny-story.jpg', NOW()),

('a-confederacy-of-dunces', 'A Confederacy of Dunces', 'John Kennedy Toole', 'A satirical novel following the eccentric and misanthropic Ignatius J. Reilly as he navigates the absurdities of 1960s New Orleans.', 'Literary Fiction', 'a-confederacy-of-dunces.jpg', NOW()),
('hyperbole-and-a-half', 'Hyperbole and a Half', 'Allie Brosh', 'A collection of humorous, autobiographical essays and illustrations based on the popular blog, covering topics like depression, childhood, and dogs.', 'Humor', 'hyperbole-and-a-half.jpg', NOW()),
('tartufo', 'Tartufo', 'Molière', 'A classic French comedy about hypocrisy and deception, where a conman pretends to be a pious religious devotee to exploit a wealthy family.', 'Classic Literature', 'tartufo.jpg', NOW()),
('dirtbag-queen', 'Dirtbag, Massachusetts', 'Andy Corren', 'A raw and hilarious memoir that explores Corren’s unconventional life, blending humor, heartbreak, and resilience.', 'Memoir', 'dirtbag-queen.jpg', NOW()),
('i-made-it-out-of-clay', 'I Made It Out of Clay', 'Beth Kander', 'A contemporary novel that explores family, identity, and tradition, following the journey of self-discovery.', 'Contemporary Fiction', 'i-made-it-out-of-clay.jpg', NOW()),

('the-book-thief', 'The Book Thief', 'Markus Zusak', 'A historical novel set in Nazi Germany, following Liesel Meminger as she steals books and shares them with others while Death narrates her story.', 'Historical Fiction', 'the-book-thief.jpg', NOW()),
('all-the-light-we-cannot-see', 'All the Light We Cannot See', 'Anthony Doerr', 'A Pulitzer Prize-winning novel about a blind French girl and a German soldier whose paths cross during World War II.', 'Historical Fiction', 'all-the-light-we-cannot-see.jpg', NOW()),
('the-nightingale', 'The Nightingale', 'Kristin Hannah', 'A gripping World War II novel that follows two sisters in Nazi-occupied France and their journey of survival and resistance.', 'Historical Fiction', 'the-nightingale.jpg', NOW()),
('outlander', 'Outlander', 'Diana Gabaldon', 'A mix of historical fiction, romance, and time travel, following Claire Randall as she is transported from 1945 to 18th-century Scotland.', 'Historical Romance', 'outlander.jpg', NOW()),
('the-help', 'The Help', 'Kathryn Stockett', 'A powerful story set in 1960s Mississippi about African American maids sharing their experiences with a young white journalist.', 'Historical Fiction', 'the-help.jpg', NOW()),

('the-big-empty', 'The Big Empty', 'Robert Crais', 'A thrilling crime novel featuring detective work, mystery, and action-packed investigation.', 'Thriller', 'the-big-empty.jpg', NOW()),
('a-very-bad-thing', 'A Very Bad Thing', 'J.T. Ellison', 'A gripping psychological thriller filled with secrets, deception, and unexpected twists.', 'Thriller', 'a-very-bad-thing.jpg', NOW()),
('in-too-deep', 'In Too Deep', 'Lee Child and Andrew Child', 'A Jack Reacher novel full of suspense and action as Reacher finds himself caught in a dangerous conspiracy.', 'Thriller', 'in-too-deep.jpg', NOW()),
('perfect-storm', 'Perfect Storm', 'Paige Shelton', 'A mystery novel with intense suspense and adventure, set in an unpredictable and stormy environment.', 'Mystery', 'perfect-storm.jpg', NOW()),
('eruption', 'Eruption', 'Michael Crichton and James Patterson', 'A thrilling disaster novel combining science, suspense, and fast-paced storytelling.', 'Science Fiction', 'eruption.jpg', NOW()),

('the-shining', 'The Shining', 'Stephen King', 'A psychological horror novel about a family’s terrifying stay at the haunted Overlook Hotel.', 'Horror', 'the-shining.jpg', NOW()),
('it', 'IT', 'Stephen King', 'A chilling story about a shape-shifting entity that terrorizes the children of Derry, Maine.', 'Horror', 'it.jpg', NOW()),
('dracula', 'Dracula', 'Bram Stoker', 'The classic Gothic horror novel that introduced Count Dracula and the legend of vampires.', 'Horror', 'dracula.jpg', NOW()),
('the-exorcist', 'The Exorcist', 'William Peter Blatty', 'A terrifying tale of demonic possession and the battle between faith and evil.', 'Horror', 'the-exorcist.jpg', NOW()),
('ghost-story', 'Ghost Story', 'Peter Straub', 'A supernatural thriller about four old men who are haunted by a horrifying secret from their past.', 'Horror', 'ghost-story.jpg', NOW()),

('solo-leveling', 'Solo Leveling', 'Chugong', 'A weak hunter gets a mysterious system that makes him the strongest.', 'Light Novel', 'solo_leveling.jpg', NOW()),
('spy-x-family', 'Spy x Family', 'Tatsuya Endo', 'A spy, an assassin, and a telepath form a fake family.', 'Manga', 'spy_x_family.jpg', NOW()),
('dan-da-dan', 'Dan Da Dan', 'Yukinobu Tatsu', 'A mix of supernatural, sci-fi, and horror with a comedic twist.', 'Manga', 'dan_da_dan.jpg', NOW()),
('jujutsu-kaisen', 'Jujutsu Kaisen', 'Gege Akutami', 'A high school student gains cursed powers and fights dark spirits.', 'Manga', 'jujutsu_kaisen.jpg', NOW()),
('blue-lock', 'Blue Lock', 'Muneyuki Kaneshiro', 'An intense football training program to create the best striker.', 'Manga', 'blue_lock.jpg', NOW()),
('omniscient-readers-viewpoint', 'Omniscient Reader’s Viewpoint', 'Sing-Shong', 'A reader of a web novel finds himself inside the story.', 'Light Novel', 'omniscient_readers_viewpoint.jpg', NOW());

INSERT INTO `books` (`book_id`, `key_slug`, `title`, `author`, `description`, `category`, `image`, `created_at`) VALUES
(1, 'the-name-of-the-wind', 'The Name of the Wind', 'Patrick Rothfuss', 'A fantasy novel following the life of Kvothe, a gifted young man who grows into a legendary figure.', 'Fantasy', 'images/name-of-the-wind.jpg', '2025-02-22 02:16:24'),
(2, 'the-way-of-kings', 'The Way of Kings', 'Brandon Sanderson', 'The first book in The Stormlight Archive, a high-fantasy series filled with intricate world-building and powerful characters.', 'Fantasy', 'images/way-of-kings.jpg', '2025-02-22 02:16:24'),
(3, 'the-eye-of-the-world', 'The Eye of the World', 'Robert Jordan', 'The first book in The Wheel of Time series, an epic tale of magic, prophecy, and the battle between good and evil.', 'Fantasy', 'images/eye-of-the-world.jpg', '2025-02-22 02:16:24'),
(4, 'mistborn', 'Mistborn', 'Brandon Sanderson', 'A gripping fantasy novel about a revolution in a world ruled by a seemingly immortal tyrant.', 'Fantasy', 'images/mistborn.jpg', '2025-02-22 02:16:24'),
(5, 'wizards-first-rule', 'Wizard\'s First Rule', 'Terry Goodkind', 'The first book in The Sword of Truth series, following the journey of Richard Cypher as he discovers his destiny.', 'Fantasy', 'images/wizards-first-rule.jpg', '2025-02-22 02:16:24'),
(6, 'red-white-royal-blue', 'Red, White & Royal Blue', 'Casey McQuiston', 'A romantic comedy about the First Son of the United States and a British prince who go from rivals to lovers.', 'Romance', 'images/red-white-royal-blue.jpg', '2025-02-22 02:16:24'),
(7, 'book-lovers', 'Book Lovers', 'Emily Henry', 'A witty, heartwarming romance following a literary agent and a brooding editor who keep running into each other.', 'Romance', 'images/book-lovers.jpg', '2025-02-22 02:16:24'),
(8, 'the-hating-game', 'The Hating Game', 'Sally Thorne', 'A charming enemies-to-lovers workplace romance between two competitive co-workers.', 'Romance', 'images/the-hating-game.jpg', '2025-02-22 02:16:24'),
(9, 'happy-place', 'Happy Place', 'Emily Henry', 'A second-chance romance about a once-perfect couple pretending to still be together during a vacation with friends.', 'Romance', 'images/happy-place.jpg', '2025-02-22 02:16:24'),
(10, 'funny-story', 'Funny Story', 'Emily Henry', 'A delightful and emotional romance about unexpected love and finding humor in heartbreak.', 'Romance', 'images/funny-story.jpg', '2025-02-22 02:16:24'),
(11, 'a-confederacy-of-dunces', 'A Confederacy of Dunces', 'John Kennedy Toole', 'A satirical novel following the eccentric and misanthropic Ignatius J. Reilly as he navigates the absurdities of 1960s New Orleans.', 'Humor', 'images/a-confederacy-of-dunces.jpg', '2025-02-22 02:16:24'),
(12, 'hyperbole-and-a-half', 'Hyperbole and a Half', 'Allie Brosh', 'A collection of humorous, autobiographical essays and illustrations based on the popular blog, covering topics like depression, childhood, and dogs.', 'Humor', 'images/hyperbole-and-a-half.jpg', '2025-02-22 02:16:24'),
(13, 'tartufo', 'Tartufo', 'Molière', 'A classic French comedy about hypocrisy and deception, where a conman pretends to be a pious religious devotee to exploit a wealthy family.', 'Humor', 'images/tartufo.jpg', '2025-02-22 02:16:24'),
(14, 'dirtbag-queen', 'Dirtbag, Massachusetts', 'Andy Corren', 'A raw and hilarious memoir that explores Corren’s unconventional life, blending humor, heartbreak, and resilience.', 'Humor', 'images/dirtbag-queen.jpg', '2025-02-22 02:16:24'),
(15, 'i-made-it-out-of-clay', 'I Made It Out of Clay', 'Beth Kander', 'A contemporary novel that explores family, identity, and tradition, following the journey of self-discovery.', 'Humor', 'images/i-made-it-out-of-clay.jpg', '2025-02-22 02:16:24'),
(16, 'the-book-thief', 'The Book Thief', 'Markus Zusak', 'A historical novel set in Nazi Germany, following Liesel Meminger as she steals books and shares them with others while Death narrates her story.', 'Historical Fiction', 'images/the-book-thief.jpg', '2025-02-22 02:16:24'),
(17, 'all-the-light-we-cannot-see', 'All the Light We Cannot See', 'Anthony Doerr', 'A Pulitzer Prize-winning novel about a blind French girl and a German soldier whose paths cross during World War II.', 'Historical Fiction', 'images/all-the-light-we-cannot-see.jpg', '2025-02-22 02:16:24'),
(18, 'the-nightingale', 'The Nightingale', 'Kristin Hannah', 'A gripping World War II novel that follows two sisters in Nazi-occupied France and their journey of survival and resistance.', 'Historical Fiction', 'images/the-nightingale.jpg', '2025-02-22 02:16:24'),
(19, 'outlander', 'Outlander', 'Diana Gabaldon', 'A mix of historical fiction, romance, and time travel, following Claire Randall as she is transported from 1945 to 18th-century Scotland.', 'Historical Fiction', 'images/outlander.jpg', '2025-02-22 02:16:24'),
(20, 'the-help', 'The Help', 'Kathryn Stockett', 'A powerful story set in 1960s Mississippi about African American maids sharing their experiences with a young white journalist.', 'Historical Fiction', 'images/the-help.jpg', '2025-02-22 02:16:24'),
(21, 'the-big-empty', 'The Big Empty', 'Robert Crais', 'A thrilling crime novel featuring detective work, mystery, and action-packed investigation.', 'Thriller', 'images/the-big-empty.jpg', '2025-02-22 02:16:24'),
(22, 'a-very-bad-thing', 'A Very Bad Thing', 'J.T. Ellison', 'A gripping psychological thriller filled with secrets, deception, and unexpected twists.', 'Thriller', 'images/a-very-bad-thing.jpg', '2025-02-22 02:16:24'),
(23, 'in-too-deep', 'In Too Deep', 'Lee Child and Andrew Child', 'A Jack Reacher novel full of suspense and action as Reacher finds himself caught in a dangerous conspiracy.', 'Thriller', 'images/in-too-deep.jpg', '2025-02-22 02:16:24'),
(24, 'perfect-storm', 'Perfect Storm', 'Paige Shelton', 'A mystery novel with intense suspense and adventure, set in an unpredictable and stormy environment.', 'Thriller', 'images/perfect-storm.jpg', '2025-02-22 02:16:24'),
(25, 'eruption', 'Eruption', 'Michael Crichton and James Patterson', 'A thrilling disaster novel combining science, suspense, and fast-paced storytelling.', 'Thriller', 'images/eruption.jpg', '2025-02-22 02:16:24'),
(26, 'the-shining', 'The Shining', 'Stephen King', 'A psychological horror novel about a family’s terrifying stay at the haunted Overlook Hotel.', 'Horror', 'images/the-shining.jpg', '2025-02-22 02:16:24'),
(27, 'it', 'IT', 'Stephen King', 'A chilling story about a shape-shifting entity that terrorizes the children of Derry, Maine.', 'Horror', 'images/it.jpg', '2025-02-22 02:16:24'),
(28, 'dracula', 'Dracula', 'Bram Stoker', 'The classic Gothic horror novel that introduced Count Dracula and the legend of vampires.', 'Horror', 'images/dracula.jpg', '2025-02-22 02:16:24'),
(29, 'the-exorcist', 'The Exorcist', 'William Peter Blatty', 'A terrifying tale of demonic possession and the battle between faith and evil.', 'Horror', 'images/the-exorcist.jpg', '2025-02-22 02:16:24'),
(30, 'ghost-story', 'Ghost Story', 'Peter Straub', 'A supernatural thriller about four old men who are haunted by a horrifying secret from their past.', 'Horror', 'images/ghost-story.jpg', '2025-02-22 02:16:24'),
(31, 'the-light-fantastic', 'The Light Fantastic', 'Terry Pratchett', 'The second book in the Discworld series, following Rincewind and Twoflower on a magical adventure.', 'Fantasy', 'images/light-fantastic-cover.jpg', '2025-02-22 15:10:36'),
(32, 'solo-leveling', 'Solo Leveling', 'Chugong', 'A weak hunter gets a mysterious system that makes him the strongest.', 'Light Novel', 'images/solo_leveling.jpg', NOW()),
(33, 'spy-x-family', 'Spy x Family', 'Tatsuya Endo', 'A spy, an assassin, and a telepath form a fake family.', 'Manga', 'images/spy_x_family.jpg', NOW()),
(34, 'dan-da-dan', 'Dan Da Dan', 'Yukinobu Tatsu', 'A mix of supernatural, sci-fi, and horror with a comedic twist.', 'Manga', 'images/dan_da_dan.jpg', NOW()),
(35, 'jujutsu-kaisen', 'Jujutsu Kaisen', 'Gege Akutami', 'A high school student gains cursed powers and fights dark spirits.', 'Manga', 'images/jujutsu_kaisen.jpg', NOW()),
(36, 'blue-lock', 'Blue Lock', 'Muneyuki Kaneshiro', 'An intense football training program to create the best striker.', 'Manga', 'images/blue_lock.jpg', NOW()),
(37, 'omniscient-readers-viewpoint', 'Omniscient Reader’s Viewpoint', 'Sing-Shong', 'A reader of a web novel finds himself inside the story.', 'Light Novel', 'images/omniscient_readers_viewpoint.jpg', NOW()),
(38, 'one-piece', 'One Piece', 'Eiichiro Oda', 'A story about pirates in search of the ultimate treasure, One Piece.', 'Manga', 'images/one-piece.jpg', NOW()),
(39, 'naruto', 'Naruto', 'Masashi Kishimoto', 'A young ninja strives to become the Hokage while overcoming challenges.', 'Manga', 'images/naruto.jpg', NOW()),
(40, 'bleach', 'Bleach', 'Tite Kubo', 'A teenager gains Soul Reaper powers and fights against evil spirits.', 'Manga', 'images/bleach.jpg', NOW()),
(41, 'attack-on-titan', 'Attack on Titan', 'Hajime Isayama', 'Humanity fights for survival against giant humanoid Titans.', 'Manga', 'images/attack-on-titan.jpg', NOW()),
(42, 'demon-slayer', 'Demon Slayer', 'Koyoharu Gotouge', 'A young swordsman battles demons to save his sister and avenge his family.', 'Manga', 'images/demon-slayer.jpg', NOW()),
(43, 'death-note', 'Death Note', 'Tsugumi Ohba', 'A student discovers a notebook that grants the power to kill anyone.', 'Manga', 'images/death-note.jpg', NOW()),
(44, 'dragon-ball', 'Dragon Ball', 'Akira Toriyama', 'A martial artist embarks on adventures to find mystical Dragon Balls.', 'Manga', 'images/dragon-ball.jpg', NOW());